### ISSUE TITLE
Errors while decoding with padding

### ISSUE THREAD

**Issue by davidcsi** [jons/base64url#2]
Hello, i¡m getting errors when decoding:

```DgvkCrkyBNSy9yHP1Yznyc2DkHTIUXaO6NlEw4CSq0E=```

It seems that "=" sign is messing up the decoding...

**Comment by davidcsi** [comment]
if i try to decode

"DgvkCrkyBNSy9yHP1Yznyc2DkHTIUXaO6NlEw4CSq0E="

by just removing "=" i also get an error

**Comment by jons** [comment]
that doesn't appear to have any characters in it that require base64url specifically, so: if i check it with regular base64, it looks like this:
```
jon@stray:~/base64url$ echo -n "DgvkCrkyBNSy9yHP1Yznyc2DkHTIUXaO6NlEw4CSq0E=" | base64 -d | hexdump -C
00000000  0e 0b e4 0a b9 32 04 d4  b2 f7 21 cf d5 8c e7 c9  |.....2....!.....|
00000010  cd 83 90 74 c8 51 76 8e  e8 d9 44 c3 80 92 ab 41  |...t.Qv...D....A|
00000020
```
however if i check it with the decoder tool included with the library, i get this:
```
jon@stray:~/base64url$ echo -n "DgvkCrkyBNSy9yHP1Yznyc2DkHTIUXaO6NlEw4CSq0E=" | ./codec/rb64ud | hexdump -C
00000000  0e 0b e4 0a b9 32 04 d4  b2 f7 21 cf d5 8c e7 c9  |.....2....!.....|
00000010  cd 83 90 74 c8 51 76 8e  e8 d9 44 c3 80 92 ab 40  |...t.Qv...D....@|
00000020  e3                                                |.|
00000021
```
they are the same, except for the ending, which does indicate a bug. do you know the expected byte sequence?

**Comment by jons** [comment]
fixed
